# Here I will be learning Data Science

## Numpy

In [1]:
my_list=[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [11]:
my_mat=[[1,'si',3],[4,5,6]]

In [12]:
my_mat

[[1, 'si', 3], [4, 5, 6]]

In [13]:
np.array(my_mat)

array([['1', 'si', '3'],
       ['4', '5', '6']], dtype='<U21')

# dekh bhi type iko reha but saare string ch hogi

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Tab dabaake ohde functions wagera aa jande aa

In [30]:
np.random.rand(5,5) # random distributed between 0 and 1

array([[0.6438128 , 0.3567421 , 0.09715464, 0.93745399, 0.84767199],
       [0.6077958 , 0.16844829, 0.11069708, 0.37192538, 0.72739947],
       [0.98680708, 0.8711679 , 0.82986931, 0.55374639, 0.16307187],
       [0.94163835, 0.8521391 , 0.13136083, 0.70052385, 0.56372662],
       [0.1672618 , 0.63476587, 0.39136437, 0.91282628, 0.99995173]])

In [33]:
np.random.randn(10,10)

array([[ 0.03505398,  1.50166669, -0.21869199,  1.40792502,  1.48273574,
        -0.77137263,  0.46867169,  2.09304723, -0.38966335, -0.29034923],
       [ 0.17362805, -1.37953439, -1.09668267,  0.06840562, -0.63880333,
        -1.15664128, -1.72100255,  0.03110177, -1.35737654,  0.704057  ],
       [ 0.49414365, -1.3824556 ,  0.95537562,  0.73410367, -1.0399967 ,
        -0.86375019,  0.81882396,  0.6417595 , -0.79759067,  2.14271282],
       [ 1.24660765,  1.09195342, -0.53491595, -0.67534515, -0.88986597,
        -1.95609388,  0.45652581, -0.53178095,  0.65461494, -1.56273843],
       [ 0.62826457,  0.2332612 ,  1.14035799, -0.76578164,  0.64138169,
        -0.09955528, -1.10740503, -0.89107644,  2.03675152,  0.23264632],
       [ 0.67899197,  0.57224618,  0.4475864 ,  0.84245182,  1.19569651,
        -0.78169579,  0.51689391,  0.52913975,  0.29712713, -0.8268846 ],
       [ 0.75449718, -0.32650105, -0.65030387,  0.36889582, -0.45074048,
        -0.62715898,  0.45493759,  1.2870639 ,  1.26762701,  0.55345339],
       [ 1.14782512, -0.41178   , -1.28663921, -0.77662928,  0.02085972,
         0.00868762,  1.1856944 , -0.31354908,  0.76912961,  0.0809785 ],
       [ 0.87286624, -0.93219621, -0.83632459,  1.39523278, -0.7420622 ,
         1.70129838, -0.13703659,  0.09753149, -0.60407573, -2.30845784],
       [-1.16040497, -0.72692433, -0.27403273, -1.7599664 , -0.33024523,
         0.4100051 ,  0.97086885,  0.588017  , -0.28382898, -1.66428432]])

In [34]:
# shift + tab will tell ke kehri kehri cheezan kar sakde o

In [37]:
np.random.randint(1,100,5)

array([71, 28, 87, 23, 74])

In [38]:
arr=np.arange(1,26)

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [46]:
x=arr.reshape(5,5)

In [41]:
arr.max()

25

In [42]:
arr.argmax()

24

In [43]:
arr.argmin()

0

In [45]:
arr.shape

(25,)

In [47]:
x.shape

(5, 5)

In [48]:
arr.dtype

dtype('int64')

In [50]:
#Other way
from numpy.random import randint

In [52]:
randint(2,10,60)

array([5, 8, 2, 8, 9, 9, 5, 3, 5, 4, 6, 5, 7, 3, 8, 4, 2, 6, 4, 7, 4, 9,
       9, 6, 2, 5, 6, 9, 3, 5, 9, 8, 5, 3, 7, 6, 6, 9, 3, 6, 6, 6, 4, 4,
       7, 5, 7, 8, 3, 2, 4, 4, 7, 2, 3, 7, 4, 9, 2, 6])

# Indexing

In [15]:
x=np.arange(50,61)

In [54]:
x

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [55]:
x[0]

50

In [56]:
x[3:9]

array([53, 54, 55, 56, 57, 58])

In [57]:
x[5:]

array([55, 56, 57, 58, 59, 60])

In [58]:
x[5::2]

array([55, 57, 59])

In [59]:
x[0:5]=23 # ehnu kehde aa broadcast karna. Ke kise number nu change karta
          #eh original array vi khraab kar dinda. Taan dhyaan rakhna 

#x_copy=x.copy() karke copy bana leni aa

In [60]:
x

array([23, 23, 23, 23, 23, 55, 56, 57, 58, 59, 60])

In [63]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [64]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr_2d[0][0]

1

In [66]:
arr_2d[0]

array([1, 2, 3])

In [67]:
arr_2d[1,1]

5

In [69]:
arr_2d[:2,1:]# :2 matlab 0 and 1 excluding 2 . 1: columns from 1 onwards

array([[2, 3],
       [5, 6]])

In [70]:
arr_2d[1:,2:]

array([[6],
       [9]])

In [71]:
y=np.arange(1,11)

In [72]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
y>5 # Will recieve a boolean value

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [75]:
z= y>6

In [77]:
y[z] #Ofcourse

array([ 7,  8,  9, 10])

In [78]:
y[y>7] #for conditional selection

array([ 8,  9, 10])

# y>7
# [1 > 7, 2 > 7, 3 > 7, 4 > 7, 5 > 7, 6 > 7, 7 > 7, 8 > 7, 9 > 7, 10 > 7]
# [False False False False False False False True True True]
# now y[False False False False False False False True True True] means give me only where y is true

### Numpy Operations

In [80]:
x+x

array([ 46,  46,  46,  46,  46, 110, 112, 114, 116, 118, 120])

In [81]:
x*x

array([ 529,  529,  529,  529,  529, 3025, 3136, 3249, 3364, 3481, 3600])

In [82]:
x*4

array([ 92,  92,  92,  92,  92, 220, 224, 228, 232, 236, 240])

In [83]:
x+100

array([123, 123, 123, 123, 123, 155, 156, 157, 158, 159, 160])

In [84]:
x-38

array([-15, -15, -15, -15, -15,  17,  18,  19,  20,  21,  22])

In [85]:
x**2

array([ 529,  529,  529,  529,  529, 3025, 3136, 3249, 3364, 3481, 3600])

In [86]:
np.sqrt(x)

array([4.79583152, 4.79583152, 4.79583152, 4.79583152, 4.79583152,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669])

In [87]:
np.max(x)

60

In [88]:
np.sin(x)

array([-0.8462204 , -0.8462204 , -0.8462204 , -0.8462204 , -0.8462204 ,
       -0.99975517, -0.521551  ,  0.43616476,  0.99287265,  0.63673801,
       -0.30481062])

In [89]:
np.log(x)

array([3.13549422, 3.13549422, 3.13549422, 3.13549422, 3.13549422,
       4.00733319, 4.02535169, 4.04305127, 4.06044301, 4.07753744,
       4.09434456])

## Pandas

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
labels=['a','b','c']

In [5]:
my_data=[10,20,30]

In [6]:
arr=np.array(my_data)

In [7]:
d={'a':10,'b':20,'c':30}

In [8]:
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [10]:
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(data=labels,index=my_data) #Series can hold any type of data as shown like can hold strings

10    a
20    b
30    c
dtype: object

In [12]:
# data te index order ch hi hai so sidha keh sakde aa

pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [20]:
pd.Series(x)

0     50
1     51
2     52
3     53
4     54
5     55
6     56
7     57
8     58
9     59
10    60
dtype: int64

In [21]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [22]:
pd.Series(data=[sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

# Pandas DataFrames

In [41]:
from numpy.random import randint

In [42]:
np.random.seed(42)

In [140]:
df=pd.DataFrame(randint(0,100,(5,4)),['A','B','C','D','E'],['W','X','Y','Z'])#a,b.. index aa, w,x..column aa

In [141]:
df

    W   X   Y   Z
A   1  63  59  20
B  32  75  57  21
C  88  48  90  58
D  41  91  59  79
E  14  61  61  46

In [47]:
df['W'] # eve karke tussi column fadd sakde o DataFrame toh

A    51
B    60
C    74
D    23
E     1
Name: W, dtype: int64

In [48]:
type(df)

pandas.core.frame.DataFrame

In [49]:
type(df['W'])

pandas.core.series.Series

In [51]:
df[['W','Z']]

    W   Z
A  51  71
B  60  86
C  74  99
D  23  52
E   1  37

In [55]:
# to drop a column
# df.drop('W') # this will give error kyonke shift + tab kar. Taan sidha axis=0 hai matlab
               # row nu drop karan bhajj janda oh
df.drop('W',axis=1)

    X   Y   Z
A  92  14  71
B  20  82  86
C  74  87  99
D   2  21  52
E  87  29  37

In [ ]:
#df.drop original cho drop nahi karda wa

In [56]:
df

    W   X   Y   Z
A  51  92  14  71
B  60  20  82  86
C  74  74  87  99
D  23   2  21  52
E   1  87  29  37

In [57]:
# inplace=True means:

# “Make the change directly to the original DataFrame instead of creating a new one.”

# eh taan hunda ke enni mushakkat toh baad eve drop na maardo tussi column

df.drop('W',axis=1,inplace=True)

In [58]:
df

    X   Y   Z
A  92  14  71
B  20  82  86
C  74  87  99
D   2  21  52
E  87  29  37

In [59]:
df.drop('E')

    X   Y   Z
A  92  14  71
B  20  82  86
C  74  87  99
D   2  21  52

In [60]:
df

    X   Y   Z
A  92  14  71
B  20  82  86
C  74  87  99
D   2  21  52
E  87  29  37

In [61]:
df.drop('E',inplace=True)

In [62]:
df

    X   Y   Z
A  92  14  71
B  20  82  86
C  74  87  99
D   2  21  52

In [63]:
df.shape

(4, 3)

Dekh ke 0th index te hai no. of rows so axis=0 is rows

In [64]:
df['X'] # Returns a Series ( 1 D )
#Give me the column named "X".

A    92
B    20
C    74
D     2
Name: X, dtype: int64

In [65]:
df[['X']] # Returns a DataFrame 
#Give me a DataFrame containing these columns

    X
A  92
B  20
C  74
D   2

In [66]:
type(df['X'])

pandas.core.series.Series

In [67]:
type(df[['X']])

pandas.core.frame.DataFrame

In [68]:
# so df[X,Y] wont work

In [69]:
df[['X','Y']]

    X   Y
A  92  14
B  20  82
C  74  87
D   2  21

In [72]:
# Cant call rows like this

In [73]:
df.loc['A']      # loc for location

X    92
Y    14
Z    71
Name: A, dtype: int64

In [76]:
df.iloc[1]      # index 1

X    20
Y    82
Z    86
Name: B, dtype: int64

In [77]:
df.loc['A','Y']

14

In [80]:
df.iloc[0,1]

14

In [82]:
df.loc[['A','D'],['X','Y']]# row a and b , column x and y. A and D not A to D

    X   Y
A  92  14
D   2  21

In [83]:
df>0

      X     Y     Z
A  True  True  True
B  True  True  True
C  True  True  True
D  True  True  True

In [86]:
df>50

       X      Y     Z
A   True  False  True
B  False   True  True
C   True   True  True
D  False  False  True

In [91]:
bool_df=df>50

In [92]:
df[bool_df]

      X     Y   Z
A  92.0   NaN  71
B   NaN  82.0  86
C  74.0  87.0  99
D   NaN   NaN  52

In [93]:
# But appan jehre project kare aa uss ch eve alag alag krke nahi kare hoye

In [94]:
df[df>50] # Projects ch eve kreya hoya assi

      X     Y   Z
A  92.0   NaN  71
B   NaN  82.0  86
C  74.0  87.0  99
D   NaN   NaN  52

In [95]:
# par eve vi nahi hunda aa
# hunda eve aa ke specific row ya column toh puchya janda

In [99]:
# df['Z',axis=1]>85

# Aaah galat aa kyonke axis=1 functions ch varteya janda

In [100]:
df['Z']>85

A    False
B     True
C     True
D    False
Name: Z, dtype: bool

In [104]:
df[df['Z']>85] # puri row aau

    X   Y   Z
B  20  82  86
C  74  87  99

In [121]:
df[df['Z']>85]['Z'] # je kalli ohi row chahidi aa

B    86
C    99
Name: Z, dtype: int64

In [124]:
df[df['Z']>85][['Z','Y']]

    Z   Y
B  86  82
C  99  87

In [122]:
df['Z'][df['Z'] > 85]
# df['Z'] = Z column 
# df['Z'][Bool]
# z column ch bool sirf

B    86
C    99
Name: Z, dtype: int64

In [108]:
df['Z']

A    71
B    86
C    99
D    52
Name: Z, dtype: int64

In [109]:
result_dff=df[df['Z']>85]

In [110]:
result_dff

    X   Y   Z
B  20  82  86
C  74  87  99

In [111]:
result_dff['Z']

B    86
C    99
Name: Z, dtype: int64

In [ ]:
# ya eve karlo

In [113]:
result_dff['X']

B    20
C    74
Name: X, dtype: int64

In [118]:
df[df['X']>50]

    X   Y   Z
A  92  14  71
C  74  87  99

In [119]:
df[df['X']>50]['X'] # Eh same ohi utte aali cheez

A    92
C    74
Name: X, dtype: int64

In [125]:
# df[bool] hamesha fertoh dataframe de dinda vapas

In [127]:
df[(df['X']>50) & (df['Y']>50)]

    X   Y   Z
C  74  87  99

In [129]:
df[(df['X']>50) & (df['Y']>50)]
# & use ho reha and nahi, te multiple conditions paranthesis ch pass hongiaan
# and iss liye nahi use ho reha bhi bass manla ke oh confuse ho janda bhi enne bool kive aa gaye

    X   Y   Z
C  74  87  99

In [130]:
df[(df['X']>50) | (df['Y']>50)] # | - or fn hai

    X   Y   Z
A  92  14  71
B  20  82  86
C  74  87  99

In [138]:
df

   level_0 index   X   Y   Z
0        0     A  92  14  71
1        1     B  20  82  86
2        2     C  74  87  99
3        3     D   2  21  52

In [146]:
# hun index A,B wagera hai.Ehnu reset karan nu

df.reset_index() # temporary aa

  index   W   X   Y   Z
0     A   1  63  59  20
1     B  32  75  57  21
2     C  88  48  90  58
3     D  41  91  59  79
4     E  14  61  61  46

In [148]:
df.reset_index(inplace=True)

In [152]:
df.drop(['index'],axis=1,inplace=True)

In [153]:
df

    W   X   Y   Z
0   1  63  59  20
1  32  75  57  21
2  88  48  90  58
3  41  91  59  79
4  14  61  61  46

In [168]:
cities='Ag og eg lo gg'.split()

In [169]:
df['States']=cities # creates new columns

In [165]:
df

    W   X   Y   Z States
0   1  63  59  20     Ag
1  32  75  57  21     og
2  88  48  90  58     eg
3  41  91  59  79     lo
4  14  61  61  46     gg

In [170]:
df.set_index('States')

         W   X   Y   Z
States
Ag       1  63  59  20
og      32  75  57  21
eg      88  48  90  58
lo      41  91  59  79
gg      14  61  61  46

In [171]:
df

    W   X   Y   Z States
0   1  63  59  20     Ag
1  32  75  57  21     og
2  88  48  90  58     eg
3  41  91  59  79     lo
4  14  61  61  46     gg

In [1]:
import numpy as np

In [7]:
import pandas as pd
from numpy.random import randn

In [8]:
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_index=list(zip(outside,inside))
hier_index=pd.MultiIndex.from_tuples(hier_index)

In [9]:
df=pd.DataFrame(randn(6,2),hier_index,['A','B'])

In [10]:
df

             A         B
G1 1 -0.085399  0.044649
   2 -1.069717 -1.266871
   3 -0.957808  0.433792
G2 1 -0.785258  0.188795
   2 -0.510110 -0.415494
   3  1.572518  0.912256

In [16]:
df.loc['G1']['A'][1]

-0.0853985898602677

# Missing Data in Pandas

In [18]:
d={'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
# eh dictionary bananda
#Column A --> [1,2,NaN]

In [19]:
df=pd.DataFrame(d)
# eh utte aali dictionary nu dataframe ch badal dinda

# pandas assumes:
# Dictionary keys become column names.

In [20]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [21]:
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [23]:
df.dropna()

#will drop any row with any missing values

     A    B  C
0  1.0  5.0  1

In [24]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [25]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [27]:
df.dropna(thresh=2)

#matlab ke threshold lagaata ke 2 values missing hon row ch taan hi drop krna hai

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [28]:
#Hamesha Shift + Tab lagaake pata krlo ke inplace= True taan nahi likhna kite

In [30]:
df.fillna(value='Fill Value')

            A           B  C
0         1.0         5.0  1
1         2.0  Fill Value  2
2  Fill Value  Fill Value  3

In [31]:
df['A']

0    1.0
1    2.0
2    NaN
Name: A, dtype: float64

In [33]:
df['A'].fillna(df['A'].mean())

# Uss row di mean value chadhaa ti aa

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# GroupBy

Allows you to groupby rows based of a column then perform some aggregate function on them

Aggregate fn is just that takes a bunch of values and spits out a single value

In [34]:
data={
    'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
     'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
      'Sales':[200,120,340,124,243,350]
     }

In [35]:
df=pd.DataFrame(data)

In [36]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [44]:
df.groupby('Company')['Sales'].sum()

# Company de layi sales nu groupby karna hai

# Matlab ('') wala column show karo then agge [''] eh aala column


# Step 1: df.groupby('Company')

# Group rows having the same company together.

# Google:
# 100
# 200

# Amazon:
# 150
# 250
# 300

# Step 2: ['Sales']

# From each group, select only the Sales column.

# So now pandas sees:

# Google Sales:
# 100
# 200

# Amazon Sales:
# 150
# 250
# 300

# Step 3: .describe()

# Calculate summary statistics for each group.

# Pandas computes:

# * count → number of values
# * mean → average
# * std → standard deviation
# * min → minimum
# * 25% → first quartile
# * 50% → median
# * 75% → third quartile
# * max → maximum

#          count   mean       std    min    25%    50%    75%    max
# Company
# Amazon     3.0  233.3   76.38    150   200    250    275    300
# Google     2.0  150.0   70.71    100   125    150    175    200

Company
FB      593
GOOG    320
MSFT    464
Name: Sales, dtype: int64

In [46]:
df.groupby('Company')['Company'].sum()

Company
FB          FBFB
GOOG    GOOGGOOG
MSFT    MSFTMSFT
Name: Company, dtype: object

In [50]:
df.groupby('Company').max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [51]:
df.groupby('Company')['Sales'].max()

Company
FB      350
GOOG    200
MSFT    340
Name: Sales, dtype: int64

In [52]:
 df.groupby('Company').describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [53]:
 df.groupby('Company')['Sales'].describe()

         count   mean         std    min     25%    50%     75%    max
Company
FB         2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG       2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT       2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [54]:
 df.groupby('Company')['Sales'].describe().transpose()

#mere saab naal eve transpose karke sahi rehnda

Company          FB        GOOG        MSFT
count      2.000000    2.000000    2.000000
mean     296.500000  160.000000  232.000000
std       75.660426   56.568542  152.735065
min      243.000000  120.000000  124.000000
25%      269.750000  140.000000  178.000000
50%      296.500000  160.000000  232.000000
75%      323.250000  180.000000  286.000000
max      350.000000  200.000000  340.000000

In [55]:
 df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [56]:
import numpy as np

In [57]:
import pandas as pd

In [58]:
# pd.concat to concatinate
# mostly columns honge taan axis=1

In [59]:
# To merge the tables
# Table A has column M,N,O and 
# Table B has column O,P,Q
# taan 0 te merge ho sakda na  ke m,n,o,p,q bann jaan column te 2 table judd ke 1 bann jaan

In [61]:
dict1={
    'A':[1,2,3],
    'B':[4,5,6],
    'C':[7,8,9]
    }

In [67]:
xcv=pd.DataFrame(dict1)

In [75]:
dict2={
    'D':[0,-1,-2],
    'E':[-3,-4,-5],
    'C':[7,8,9]
    }

In [76]:
vbn=pd.DataFrame(dict2)

In [78]:
pd.merge(xcv,vbn,on='C')

   A  B  C  D  E
0  1  4  7  0 -3
1  2  5  8 -1 -4
2  3  6  9 -2 -5

# Joining

Merge wangu hi hai bass index raahi hunda na ke columns raahi

In [81]:
# .join()

.join() is used to combine two DataFrames based on their index (by default).

In [88]:
df1 = pd.DataFrame({
    'A': [1, 2, 3]
}, index=['a', 'c', 'b'])

df2 = pd.DataFrame({
    'B': [4, 5, 6]
}, index=['a', 'b', 'c'])

In [89]:
df1

   A
a  1
c  2
b  3

In [90]:
df2

   B
a  4
b  5
c  6

In [91]:
df1.join(df2)
# Index de basis te join karta

   A  B
a  1  4
c  2  6
b  3  5

In [87]:
pd.concat([df1,df2],axis=1)

   A  B
a  1  4
b  2  5
c  3  6

In [92]:
# Etho join te concat da difference pata lagg gaya

In [93]:
# Concat simply combines

# Pandas Operations

In [94]:
df=pd.DataFrame({'col1':[1,2,3,4],
                'col2':[444,555,666,444],
                'col3':['abc','def','ghi','jkl']
                })

In [95]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  jkl

In [96]:
df['col2'].unique()

array([444, 555, 666])

In [97]:
df['col2'].nunique() # No. of unique values

3

In [98]:
df['col2'].value_counts() # kehri cheez kinni vaar aayi wa

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [100]:
df['col1']>2

0    False
1    False
2     True
3     True
Name: col1, dtype: bool

In [101]:
df[df['col1']>2]

   col1  col2 col3
2     3   666  ghi
3     4   444  jkl

In [103]:
df[df['col1']>2]['col1']

2    3
3    4
Name: col1, dtype: int64

In [111]:
df[(df['col1']>2) & (df['col2']>450)]

   col1  col2 col3
2     3   666  ghi

In [110]:
df[(df['col1'] > 2) & (df['col2'] > 450)]

   col1  col2 col3
2     3   666  ghi

In [112]:
def times2(x):
    return x*2

In [114]:
df['col2'].apply(times2)
#Eve func banaake vi apply kar sakde aa

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [116]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [117]:
# Easy way ki hai apply da ---- lambda function. Function da easy way hunda lambda

df['col2'].apply(lambda x:x*2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [118]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  jkl

In [119]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [124]:
df.sort_values('col2')

   col1  col2 col3
0     1   444  abc
3     4   444  jkl
1     2   555  def
2     3   666  ghi

In [125]:
df.isnull()

    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [126]:
# pivot_table naam di kuj cheez hundi aa

# Pandas Input and Output

In [129]:
# pd.read_ 

# tab dabaake pata laalo kehra kehra hai

In [130]:
# df.to_

# kis kis ch change ho sakdi aa
# index=False karna warna index vi dikhaange

In [131]:
# pd.read_excel('Excel sheet name',sheetname='Sheet1')

# Jive alag alag sheets hundi hai na bhi sheet 1,sheet 2. Vese default sheet 1 hundi aa par je sheet 2 padhna taan eve krlo

# je df.to_excel('new excel name',sheetname='NewSheet') je new sheet banaani aa taan sheetname vi add krna penda

In [132]:
# html link vi read kar sakde o net toh.

# pd.read_html('html link')

In [133]:
# sql ch naal engine vi aanda